import { computed, reactive } from "vue"

const messages = {
  ja: {
    language: "言語",
    japanese: "日本語",
    english: "English",
    home: "ホームに戻る",
    guide: "ガイドを見る",
    create: "漫画を作る",
    homeTagline: "Markdownから漫画を作ろう。",
    homeDescription: "独自Markdownを書くだけで漫画をレイアウト。吹き出し・画像・背景・コマ割りを自由に配置し、リアルタイムプレビューを見ながら編集できます。",
    back: "戻る",
    uploadImage: "画像をアップロード",
    addPanel: "＋ コマを追加",
    addText: "＋ テキストを追加",
    editor: "編集",
    preview: "プレビュー",
    publish: "出力する →",
    visualEditor: "ビジュアルエディター",
    arrange: "コマ、吹き出し、しっぽ、画像を視覚的に配置できます。",
    text: "テキスト",
    deleteText: "テキストを削除",
    panel: "コマ",
    deletePanel: "コマを削除",
    plainText: "普通の文章を入力",
    backgroundColor: "背景色",
    border: "枠線",
    solid: "実線",
    dashed: "破線",
    none: "なし",
    borderWidth: "枠線幅",
    leftPx: "左位置 (px)",
    topPx: "上位置 (px)",
    widthPx: "幅 (px)",
    heightPx: "高さ (px)",
    bubble: "吹き出し",
    remove: "削除",
    shape: "形",
    layer: "レイヤー",
    leftPercent: "左位置 (%)",
    topPercent: "上位置 (%)",
    fill: "塗り",
    show: "表示",
    hide: "非表示",
    body: "本文",
    bubbleText: "吹き出しの文章",
    fontSize: "文字サイズ",
    direction: "方向",
    horizontal: "横書き",
    vertical: "縦書き",
    bodyX: "本文 X (%)",
    bodyY: "本文 Y (%)",
    triangle: "三角",
    circle: "丸",
    angle: "角度",
    scale: "倍率",
    distance: "距離",
    addTail: "＋ しっぽを追加",
    image: "画像",
    addBubble: "＋ 吹き出し",
    addImage: "＋ 画像",
    publishTitle: "公開",
    publishSubtitle: "公開前に漫画を確認します。",
    copy: "コピー",
    output: "出力する",
    share: "共有する",
    other: "その他",
    guideTitle: "Writing Guide",
    guideSubtitle: "独自Markdownで漫画を組み立てるためのリファレンス",
    findSyntax: "記法を探す",
    keyword: "キーワード",
    guideContents: "ガイドの目次",
    noSyntax: "該当する記法がありません。",
    guideOverview: "漫画記法の全体像",
    guideIntro: "Manga Editorの入力項目からコマ・吹き出し・画像・本文を組み立て、右側のプレビューで確認できます。下のサンプルでは、エディターが保存するMarkdown記法も確認できます。",
    copyCode: "Copy code",
    copied: "Copied",
    properties: "属性リファレンス",
    property: "属性",
    type: "型",
    description: "説明",
    defaultValue: "既定値",
    notes: "注意",
    urlLabel: "WebサイトのURLを入力",
    urlPlaceholder: "URLを入力",
    load: "読み込む",
    thinking: "Thinking...",
    enterUrl: "URLを入力してください",
    fetchFailed: "データの取得に失敗しました",
    editInEditor: "エディタで編集",
    publishNow: "このまま公開",
    uploadTitle: "画像をアップロード",
    imageName: "画像名",
    destination: "保存先",
    uncategorized: "未分類",
    newFolder: "＋ 新しいフォルダ",
    folderName: "フォルダ名",
    createFolder: "作成",
    cancel: "キャンセル",
    save: "保存",
    folderExists: "同じ名前のフォルダがあります",
    imageNameRequired: "画像名を入力してください",
    copyFailed: "コピーに失敗しました。",
    folderManagement: "⚙ フォルダ管理",
    selectImage: "画像を選択",
    move: "移動",
    rename: "名前変更",
    folderCreate: "フォルダ作成",
    folderRename: "フォルダ名変更",
    folderDelete: "フォルダ削除",
    deleteFolderQuestion: "「{name}」を削除しますか？",
    moveImagesToUncategorized: "画像を未分類へ移動",
    deleteImagesToo: "画像も削除",
    chooseDestination: "移動先を選択",
    addFolder: "＋ フォルダ追加"
    ,markdownCopied: "Markdownをコピーしました！"
    ,htmlCopied: "HTMLをコピーしました！"
    ,imageCopied: "画像をコピーしました！"
    ,imageCopyFailed: "画像コピーに失敗しました"
    ,shareUnsupported: "このブラウザは共有機能に対応していません。"
  },
  en: {
    language: "Language",
    japanese: "日本語",
    english: "English",
    home: "Back to Home",
    guide: "View Guide",
    create: "Create Manga",
    homeTagline: "Turn Markdown into Manga.",
    homeDescription: "Lay out manga by writing your own Markdown. Place bubbles, images, backgrounds, and panels freely while editing with a real-time preview.",
    back: "Back",
    uploadImage: "Upload image",
    addPanel: "+ Add panel",
    addText: "+ Add text",
    editor: "Editor",
    preview: "Preview",
    publish: "Publish →",
    visualEditor: "Visual editor",
    arrange: "Arrange panels, bubbles, tails, and images visually.",
    text: "Text",
    deleteText: "Delete text",
    panel: "Panel",
    deletePanel: "Delete panel",
    plainText: "Enter plain text",
    backgroundColor: "Background",
    border: "Border",
    solid: "Solid",
    dashed: "Dashed",
    none: "None",
    borderWidth: "Border width",
    leftPx: "Left (px)",
    topPx: "Top (px)",
    widthPx: "Width (px)",
    heightPx: "Height (px)",
    bubble: "Bubble",
    remove: "Remove",
    shape: "Shape",
    layer: "Layer",
    leftPercent: "Left (%)",
    topPercent: "Top (%)",
    fill: "Fill",
    show: "Shown",
    hide: "Hidden",
    body: "Text",
    bubbleText: "Bubble text",
    fontSize: "Font size",
    direction: "Direction",
    horizontal: "Horizontal",
    vertical: "Vertical",
    bodyX: "Text X (%)",
    bodyY: "Text Y (%)",
    triangle: "Triangle",
    circle: "Circle",
    angle: "Angle",
    scale: "Scale",
    distance: "Distance",
    addTail: "+ Add tail",
    image: "Image",
    addBubble: "+ Bubble",
    addImage: "+ Image",
    publishTitle: "Publish",
    publishSubtitle: "Review your manga before publishing.",
    copy: "Copy",
    output: "Export",
    share: "Share",
    other: "Other",
    guideTitle: "Writing Guide",
    guideSubtitle: "A reference for building manga with custom Markdown",
    findSyntax: "Find syntax",
    keyword: "Keyword",
    guideContents: "Guide contents",
    noSyntax: "No matching syntax found.",
    guideOverview: "The anatomy of manga syntax",
    guideIntro: "Build panels, bubbles, images, and text from the Manga Editor fields, then check the result in the preview. The examples below also show the Markdown syntax saved by the editor.",
    copyCode: "Copy code",
    copied: "Copied",
    properties: "Property reference",
    property: "Property",
    type: "Type",
    description: "Description",
    defaultValue: "Default",
    notes: "Notes",
    urlLabel: "Enter a website URL",
    urlPlaceholder: "Enter URL",
    load: "Load",
    thinking: "Thinking...",
    enterUrl: "Please enter a URL",
    fetchFailed: "Failed to fetch data",
    editInEditor: "Edit in editor",
    publishNow: "Publish as is",
    uploadTitle: "Upload image",
    imageName: "Image name",
    destination: "Destination",
    uncategorized: "Uncategorized",
    newFolder: "+ New folder",
    folderName: "Folder name",
    createFolder: "Create",
    cancel: "Cancel",
    save: "Save",
    folderExists: "A folder with that name already exists",
    imageNameRequired: "Please enter an image name",
    copyFailed: "Failed to copy.",
    folderManagement: "⚙ Manage folders",
    selectImage: "Select image",
    move: "Move",
    rename: "Rename",
    folderCreate: "Create folder",
    folderRename: "Rename folder",
    folderDelete: "Delete folder",
    deleteFolderQuestion: "Delete \"{name}\"?",
    moveImagesToUncategorized: "Move images to Uncategorized",
    deleteImagesToo: "Delete images too",
    chooseDestination: "Choose destination",
    addFolder: "+ Add folder"
    ,markdownCopied: "Markdown copied!"
    ,htmlCopied: "HTML copied!"
    ,imageCopied: "Image copied!"
    ,imageCopyFailed: "Failed to copy the image"
    ,shareUnsupported: "This browser does not support sharing."
  }
}

const state = reactive({
  locale: localStorage.getItem("mangadown-locale") || "ja"
})

export function useLanguage() {
  const locale = computed({
    get: () => state.locale,
    set: value => {
      state.locale = value
      localStorage.setItem("mangadown-locale", value)
    }
  })

  const t = key => messages[state.locale][key] ?? messages.ja[key] ?? key
  const toggleLocale = () => {
    locale.value = locale.value === "ja" ? "en" : "ja"
  }

  return { locale, t, toggleLocale }
}
